blank_issues_enabled: false
contact_links:
  - name: modified Support-Forum
    url: https://www.modified-shop.org/forum
    about: FÃ¼r allgemeine Fragen und Support bitte zuerst hier nachsehen oder nachfragen.
  - name: Dokumentation
    url: https://www.modified-shop.org/wiki
    about: Offizielle Dokumentation zum modified Shop System
